# Generated by Django 3.2.6 on 2021-08-25 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20210825_1248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tags',
            name='publications',
        ),
        migrations.AddField(
            model_name='tags',
            name='posts',
            field=models.ManyToManyField(related_name='tags', to='posts.Post'),
        ),
    ]
